module: recommender.models.hgt:HGT
_partial_: true
params:
  in_dims:
    user: 100 # Overridden by data
    item: 100 # Overridden by data
  metadata: null # Overridden by data
  hidden_dim: 128
  heads: 2
  layers: 2
  dropout: 0.1